(()=>{
const {esc,id,today}=App;let db=App.readCost(), selected=today(),month=selected.slice(0,7);
const root=document.getElementById('app'),dialog=document.getElementById('editor'),form=document.getElementById('entryForm');
const piece=x=>db.pieces.find(p=>p.id===x);
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const dateOf=x=>x?.slice(0,10)||'';
const duration=s=>s.end?Math.max(0,(new Date(s.end)-new Date(s.start))/3600000-num(s.breakMinutes)/60):0;
const num=x=>Math.max(0,Number(x)||0);
const hours=x=>`${Math.round(x*10)/10} 小時`;
function toast(t){const e=document.getElementById('notice');e.textContent=t;e.classList.add('on');setTimeout(()=>e.classList.remove('on'),2800)}
function save(){try{App.writeCost(db);render()}catch(e){toast('儲存失敗，請先備份資料')}}
function modal(html,cb){form.innerHTML=html+'<div class="foot"><button type="button" id="cancel">取消</button><button class="primary" type="submit">確認儲存</button></div>';form.onsubmit=e=>{e.preventDefault();try{cb(new FormData(form));dialog.close();save()}catch(err){toast(err.message||'無法儲存')}};dialog.showModal()}
form.onclick=e=>{if(e.target.id==='cancel')dialog.close()};
const field=(label,name,val='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(val||'')}" ${extra}></label>`;
const select=(label,name,opts,value)=>`<label>${label}<select name="${name}">${opts.map(([k,t])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const pieceSelect=v=>select('關聯成本作品（選填）','pieceId',[['','不指定'],...db.pieces.map(p=>[p.id,p.name])],v||'');
function monthGrid(){const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1),start=new Date(y,m-1,1-first.getDay());let cells='<div class="calendar-grid">'+['日','一','二','三','四','五','六'].map(d=>`<div class="weekday">${d}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start.getTime()+i*86400000),day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,planned=db.plans.filter(p=>p.date<=day && (p.endDate||p.date)>=day),work=db.sessions.filter(s=>dateOf(s.start)===day);cells+=`<button class="day ${d.getMonth()+1!==m?'dim':''} ${day===selected?'active':''}" data-day="${day}"><b>${d.getDate()}</b>${planned.length?`<span class="dotmark">${planned.length} 項排程</span>`:''}${work.length?`<span class="dotmark workmark">${hours(work.reduce((a,s)=>a+duration(s),0))}</span>`:''}</button>`}return cells+'</div>'}
function render(){const active=db.sessions.find(s=>!s.end),daily=db.sessions.filter(s=>dateOf(s.start)===selected),plans=db.plans.filter(p=>p.date<=selected&&(p.endDate||p.date)>=selected),total=db.sessions.filter(s=>dateOf(s.start).slice(0,7)===month).reduce((a,s)=>a+duration(s),0);
root.innerHTML=`<div class="costcard"><h3>快速記工作</h3><p>${active?`進行中：${esc(active.start.replace('T',' '))}${active.pieceId?' · '+esc(piece(active.pieceId)?.name||''):''}`:'目前沒有進行中的工作紀錄'}</p><div class="quickactions"><button class="primary" data-act="${active?'stop':'start'}">${active?'結束工作':'開始工作'}</button><button class="smallbtn" data-act="manual">補登一段時間</button></div><p class="muted">開始、結束都可選目前或自訂時間。時數不會自動計入作品成本。</p></div>
<div class="monthbar"><button data-month="-1">‹</button><b>${month.replace('-',' 年 ')} 月</b><button data-month="1">›</button></div>${monthGrid()}<div class="dashboard" style="margin-top:12px"><div class="stat"><b>${hours(total)}</b><small>本月已完成工時</small></div><div class="stat"><b>${db.plans.filter(p=>p.date.slice(0,7)===month).length} 項</b><small>本月開始的排程</small></div></div>
<div class="pagehead"><h2>${selected} 紀錄</h2><button class="primary" data-act="newPlan">＋ 排程</button></div><div class="costcard"><h3>預計排程</h3>${plans.map(p=>`<div class="rowline"><b>${esc(p.title)}</b> · ${esc(p.date)}${p.endDate&&p.endDate!==p.date?'～'+esc(p.endDate):''}${p.time?' '+esc(p.time):''}<p>${esc(piece(p.pieceId)?.name||'')} ${esc(p.note||'')}</p><div class="actions"><button data-act="editPlan" data-id="${p.id}">修改</button><button class="subtle" data-act="deletePlan" data-id="${p.id}">刪除</button></div></div>`).join('')||'<p class="muted">這天沒有排程</p>'}</div>
<div class="costcard"><h3>工作時間 · ${hours(daily.reduce((a,s)=>a+duration(s),0))}</h3>${daily.map(s=>`<div class="rowline"><b>${esc(s.start.replace('T',' '))}～${esc(s.end?.replace('T',' ')||'進行中')}</b><p>${esc(piece(s.pieceId)?.name||'')} · ${s.end?hours(duration(s)):'尚未結束'}${s.breakMinutes?' · 休息 '+s.breakMinutes+' 分':''} ${esc(s.note||'')}</p><div class="actions"><button data-act="editSession" data-id="${s.id}">修改</button><button class="subtle" data-act="deleteSession" data-id="${s.id}">刪除</button></div></div>`).join('')||'<p class="muted">這天還沒有工作紀錄</p>'}</div>`}
function clock(which){const s=db.sessions.find(x=>!x.end);modal(`<h2>確認${which==='start'?'開始':'結束'}時間</h2>${select('時間來源','source',[['now','記錄確認當下'],['custom','自訂時間']],'now')}${field('自訂時間（選自訂才使用）','custom',localNow(),'datetime-local')}${which==='start'?pieceSelect():'<p class="muted">將結束目前進行中的工作紀錄。</p>'}`,f=>{const time=f.get('source')==='now'?localNow():String(f.get('custom'));if(!time)throw Error('請選時間');if(which==='start'){if(db.sessions.some(x=>!x.end))throw Error('請先結束目前工作');db.sessions.push({id:id(),start:time,end:null,pieceId:String(f.get('pieceId')||''),breakMinutes:0,note:''});selected=dateOf(time)}else{if(!s)throw Error('沒有進行中的工作');if(new Date(time)<=new Date(s.start))throw Error('結束時間必須晚於開始');s.end=time;selected=dateOf(s.start)}})}
function sessionForm(s){s=s||{};modal(`<h2>${s.id?'修改工時':'補登工時'}</h2>${field('開始時間','start',s.start||`${selected}T09:00`,'datetime-local','required')}${field('結束時間','end',s.end||`${selected}T10:00`,'datetime-local','required')}${field('休息分鐘','breakMinutes',s.breakMinutes||0,'number','min="0" step="1"')}${pieceSelect(s.pieceId)}${field('工作內容／備註','note',s.note)}`,f=>{const start=String(f.get('start')),end=String(f.get('end')),breakMinutes=num(f.get('breakMinutes'));if(new Date(end)<=new Date(start)||new Date(end)-new Date(start)<=breakMinutes*60000)throw Error('請確認開始、結束及休息時間');Object.assign(s,{id:s.id||id(),start,end,breakMinutes,pieceId:String(f.get('pieceId')||''),note:String(f.get('note')||'')});if(!db.sessions.some(x=>x.id===s.id))db.sessions.push(s);selected=dateOf(start)})}
function planForm(p){p=p||{};modal(`<h2>${p.id?'修改排程':'新增排程'}</h2>${field('事項名稱 *','title',p.title,'text','required')}${field('開始日期','date',p.date||selected,'date','required')}${field('預計結束日期','endDate',p.endDate||p.date||selected,'date')}${field('時間（選填）','time',p.time,'time')}${pieceSelect(p.pieceId)}${field('備註','note',p.note)}`,f=>{const date=String(f.get('date')),endDate=String(f.get('endDate')||date),title=String(f.get('title')||'').trim();if(!title||endDate<date)throw Error('請確認事項名稱與日期');Object.assign(p,{id:p.id||id(),title,date,endDate,time:String(f.get('time')||''),pieceId:String(f.get('pieceId')||''),note:String(f.get('note')||'')});if(!db.plans.some(x=>x.id===p.id))db.plans.push(p);selected=date;month=date.slice(0,7)})}
root.onclick=e=>{const t=e.target.closest('[data-day],[data-month],[data-act]');if(!t)return;if(t.dataset.day){selected=t.dataset.day;month=selected.slice(0,7);render();return}if(t.dataset.month){const [y,m]=month.split('-').map(Number),d=new Date(y,m-1+Number(t.dataset.month),1);month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;selected=month+'-01';render();return}
const a=t.dataset.act,k=t.dataset.id;if(a==='start'||a==='stop')return clock(a);if(a==='manual')return sessionForm();if(a==='editSession')return sessionForm(db.sessions.find(x=>x.id===k));if(a==='newPlan')return planForm();if(a==='editPlan')return planForm(db.plans.find(x=>x.id===k));if(a==='deleteSession'&&confirm('刪除這段工作時間？')){db.sessions=db.sessions.filter(x=>x.id!==k);save()}if(a==='deletePlan'&&confirm('刪除這項排程？')){db.plans=db.plans.filter(x=>x.id!==k);save()}}
render();
})();
