(() => {
const {esc,money,num,id,today}=App;
let db=App.readCost(), tab=(['pieces','orders','products','overview'].includes((location.hash||'').slice(1))?(location.hash||'').slice(1):'pieces'), opened=null, search='';
const root=document.getElementById('app'), dialog=document.getElementById('editor'), form=document.getElementById('entryForm');
const product=x=>db.products.find(p=>p.id===x), piece=x=>db.pieces.find(p=>p.id===x);
const order=x=>db.orders.find(o=>o.id===x);
const allLines=()=>db.orders.flatMap(o=>o.lines.map(l=>({...l,date:o.date,store:o.store,orderId:o.id})));
const line=x=>allLines().find(l=>l.id===x);
const fmt=x=>x?esc(x):'—';
const stockOf=p=>p.thread?num(App.readThread().stock?.[p.thread+':'+p.color]?.skeins):num(p.stock);
function toast(t){const el=document.getElementById('notice');el.textContent=t;el.classList.add('on');setTimeout(()=>el.classList.remove('on'),2800)}
function persist(){try{App.writeCost(db);render()}catch(e){toast('儲存失敗，請先下載備份並釋出手機空間')}}
function show(html,callback){form.onclick=null;form.onchange=null;form.innerHTML=html+'<div class="foot"><button type="button" id="cancelDialog">取消</button><button class="primary" type="submit">儲存</button></div>';form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('[type=submit]');btn.disabled=true;try{await callback(new FormData(form));dialog.close();persist()}catch(err){toast(err.message||'儲存失敗');btn.disabled=false}};dialog.showModal()}
form.addEventListener('click',e=>{if(e.target.id==='cancelDialog')dialog.close()});
const field=(label,name,val='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(val)}" ${extra}></label>`;
const select=(label,name,options,value)=>`<label>${label}<select name="${name}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const photos=(ids=[])=>`<div class="cover">${ids.map(x=>`<img data-photo="${esc(x)}" alt="實物照片">`).join('')}</div>`;
async function paintPhotos(){for(const el of document.querySelectorAll('[data-photo]')){try{const src=await App.getPhoto(el.dataset.photo);if(el.isConnected && src)el.src=src}catch(_){}}}
function productPhotos(p){return photos(p?.photos||[])}
function cardsTitle(title,button,act){return `<div class="pagehead"><h2>${title}</h2>${button?`<button class="primary" data-act="${act}">${button}</button>`:''}</div>`}
function pName(pid){return esc(product(pid)?.name||'已移除商品')}
function totals(p){const material=(p.allocations||[]).reduce((s,a)=>s+(line(a.lineId)?.unitPrice||0)*num(a.percent)/100,0);const extras=(p.extras||[]).reduce((s,x)=>s+num(x.amount),0);return {material,extras,total:material+extras}}
function saleProfit(p){const s=p.sale;if(!s)return null;const c=totals(p).total;const fee=s.feeMode==='percent'?num(s.price)*num(s.feeValue)/100:num(s.feeValue);return num(s.price)+num(s.shippingCharged)-c-num(s.postage)-num(s.packaging)-fee}
function renderOverview(){let paid=0,revenue=0,profit=0;for(const o of db.orders)paid+=o.lines.reduce((s,l)=>s+num(l.unitPrice)*num(l.qty),0)+num(o.shipping)-num(o.discount);for(const p of db.pieces)if(p.sale && p.status!=='取消'){revenue+=num(p.sale.price)+num(p.sale.shippingCharged);profit+=saleProfit(p)}
return `<div class="dashboard"><div class="stat"><b>${money(paid)}</b><small>累計採購實付</small></div><div class="stat"><b>${db.pieces.length} 件</b><small>成本作品</small></div><div class="stat"><b>${money(revenue)}</b><small>已登記販售收入</small></div><div class="stat"><b>${money(profit)}</b><small>已登記作品估算利潤</small></div></div><p class="muted">採購實付與作品分攤是不同口徑，不能直接相減。利潤按各件作品的分攤、估算與實際販售費用計算。</p>`}
function renderPieces(){if(opened){const p=piece(opened);if(!p){opened=null;return renderPieces()}const c=totals(p),profit=saleProfit(p);return `${cardsTitle('成本作品')}<button class="smallbtn" data-act="closePiece">‹ 返回全部作品</button><div class="costcard">${photos(p.photos)}<h3>${esc(p.name)}</h3><p>${fmt(p.madeDate)} · <span class="pill">${esc(p.status||'待製作')}</span></p><p>${esc(p.note||'')}</p><div class="actions"><button data-act="editPiece" data-id="${p.id}">編輯作品</button><button data-act="changeStatus" data-id="${p.id}">變更進度</button><button data-act="duplicatePiece" data-id="${p.id}">複製下一件</button><button class="subtle" data-act="deletePiece" data-id="${p.id}">刪除</button></div></div>
<div class="costcard"><div class="pagehead"><h3>材料分攤 · ${money(c.material)}</h3><button class="smallbtn" data-act="addAllocation" data-id="${p.id}">＋ 材料</button></div>${(p.allocations||[]).map(a=>{const l=line(a.lineId);return `<div class="rowline"><b>${pName(l?.productId)}</b> · ${esc(a.percent)}% = ${money(num(l?.unitPrice)*num(a.percent)/100)}<p>購入單價 ${money(l?.unitPrice)} · ${esc(l?.date||'舊購買紀錄')} ${esc(l?.store||'')}</p><div class="actions"><button data-act="editAllocation" data-id="${p.id}" data-ref="${a.id}">修改</button><button class="subtle" data-act="removeAllocation" data-id="${p.id}" data-ref="${a.id}">移除</button></div></div>`}).join('')||'<p class="muted">尚未加入材料</p>'}</div>
<div class="costcard"><div class="pagehead"><h3>設計與雜項 · ${money(c.extras)}</h3><button class="smallbtn" data-act="addExtra" data-id="${p.id}">＋ 成本</button></div>${(p.extras||[]).map(x=>`<div class="rowline"><b>${esc(x.name)}</b> · ${money(x.amount)} <span class="pill">${esc(x.kind)}</span><div class="actions"><button data-act="editExtra" data-id="${p.id}" data-ref="${x.id}">修改</button><button class="subtle" data-act="removeExtra" data-id="${p.id}" data-ref="${x.id}">移除</button></div></div>`).join('')||'<p class="muted">可在雜項自行估算人工費</p>'}<p><b>作品總成本 ${money(c.total)}</b></p></div>
<div class="costcard"><div class="pagehead"><h3>販售與出貨</h3><button class="smallbtn" data-act="saleForm" data-id="${p.id}">${p.sale?'修改販售':'＋ 登記販售'}</button></div>${p.sale?`${['販售日期 '+fmt(p.sale.date),'平台 '+fmt(p.sale.platform),'售價 '+money(p.sale.price),'購買者 '+fmt(p.sale.buyer),'寄送 '+fmt(p.sale.shippingMethod),'買家付運費 '+money(p.sale.shippingCharged),'實際寄件運費 '+money(p.sale.postage),'包材費 '+money(p.sale.packaging),'平台抽成 '+(p.sale.feeMode==='percent'?esc(p.sale.feeValue)+'%':'固定 '+money(p.sale.feeValue)),'出貨日期 '+fmt(p.sale.shipDate),'訂單編號 '+fmt(p.sale.orderNo),'備註 '+fmt(p.sale.note)].map(t=>`<p>${t}</p>`).join('')}<p><b>估算利潤 ${money(profit)}</b></p>`:'<p class="muted">尚未登記販售</p>'}</div>`}
let arr=[...db.pieces].reverse().filter(p=>!search||p.name.includes(search));return `${renderOverview()}${cardsTitle('成本作品','＋ 新增作品','newPiece')}<input class="listsearch" id="search" placeholder="搜尋作品名稱" value="${esc(search)}">${arr.map(p=>`<div class="costcard">${photos(p.photos)}<h3>${esc(p.name)}</h3><p>${esc(p.madeDate||'未填日期')} · ${esc(p.status||'待製作')} · 成本 ${money(totals(p).total)}</p><div class="actions"><button data-act="openPiece" data-id="${p.id}">查看成本與販售</button><button data-act="duplicatePiece" data-id="${p.id}">複製下一件</button></div></div>`).join('')||'<div class="emptyhint">先建立第一件客製作品，再記材料與販售。</div>'}`}
function renderProducts(){const list=db.products.filter(p=>!search||[p.name,p.brand,p.category,p.color].join(' ').includes(search));return `${cardsTitle('常買商品','＋ 新商品','newProduct')}<input class="listsearch" id="search" placeholder="搜尋品名、品牌、色號" value="${esc(search)}">${list.map(p=>`<div class="costcard">${productPhotos(p)}<h3>${esc(p.name)}</h3><p>${esc([p.brand,p.category,p.color].filter(Boolean).join(' · '))} · ${esc({consume:'消耗品',reuse:'可重複使用',expense:'僅記花費'}[p.kind]||'')}</p><p>目前庫存 ${stockOf(p)} ${esc(p.unit||'個')}${p.thread?' · 已連結線盒 '+esc(p.color):''}</p>${(p.moves||[]).slice(-2).reverse().map(m=>`<p class="muted">${esc(m.date)} · ${m.action==='reuse'?'重複使用':(m.qty>0?'＋':'')+m.qty+' '+esc(p.unit||'個')} ${esc(m.note||'')}</p>`).join('')}<div class="actions"><button data-act="editProduct" data-id="${p.id}">編輯</button><button data-act="movement" data-id="${p.id}">記使用／庫存</button><button class="subtle" data-act="deleteProduct" data-id="${p.id}">刪除</button></div></div>`).join('')||'<div class="emptyhint">可先建立常買商品，以後選取就能帶入照片與資料。</div>'}`}
function renderOrders(){return `${cardsTitle('採購紀錄','＋ 登記購買','newOrder')}<p class="muted">一張訂單可加多件商品；材料分攤只取單價，整單運費與折扣留在此處。</p>${[...db.orders].sort((a,b)=>b.date.localeCompare(a.date)).map(o=>{let subtotal=o.lines.reduce((s,l)=>s+num(l.qty)*num(l.unitPrice),0);return `<div class="costcard"><h3>${esc(o.store||'未填商店')} · ${esc(o.date)}</h3><p>訂單 ${fmt(o.orderNo)} · 實付 ${money(subtotal+num(o.shipping)-num(o.discount))}（商品 ${money(subtotal)}＋運費 ${money(o.shipping)}－折扣 ${money(o.discount)}）</p>${o.lines.map(l=>`<div class="rowline">${productPhotos(product(l.productId))}${pName(l.productId)} · ${num(l.qty)} ${esc(product(l.productId)?.unit||'個')} × ${money(l.unitPrice)}<button class="smallbtn" style="margin-left:8px" data-act="editLine" data-id="${o.id}" data-ref="${l.id}">修改</button></div>`).join('')}<p>${esc(o.note||'')}</p><div class="actions"><button data-act="editOrder" data-id="${o.id}">修改訂單資料</button></div></div>`}).join('')||'<div class="emptyhint">記下第一次購買，往後可從常買商品快速加入。</div>'}`}
function render(){root.innerHTML=`<div class="sectiontabs">${[['pieces','作品與販售'],['orders','採購'],['products','商品'],['overview','總覽／備份']].map(([t,n])=>`<button data-tab="${t}" class="${t===tab?'active':''}">${n}</button>`).join('')}</div>`+(tab==='pieces'?renderPieces():tab==='products'?renderProducts():tab==='orders'?renderOrders():renderOverview()+`<div class="costcard"><h3>資料備份</h3><p>包含線盒、成本、日曆與照片；請定期下載，換手機可從備份檔還原。</p><button class="primary" data-act="backup">下載完整備份</button><label class="detail" style="display:block;margin-top:15px">選擇備份檔以還原<input type="file" id="restoreFile" accept=".json,application/json"></label></div>`);paintPhotos()}
function productForm(p){p=p||{};show(`<h2>${p.id?'編輯商品':'新增常買商品'}</h2>${field('品名 *','name',p.name,'text','required')}${field('品牌','brand',p.brand)}${select('材料分類','category',db.categories.map(x=>[x,x]).concat(p.category&&!db.categories.includes(p.category)?[[p.category,p.category]]:[]),p.category||'其他')}${field('新的材料分類（選填）','newCategory')}${select('庫存類型','kind',[['consume','消耗品'],['reuse','可重複使用'],['expense','僅記花費']],p.kind||'consume')}${field('計量單位','unit',p.unit||'個')}${select('是否為線盒繡線','thread',[['','否'],['moul','DMC 六股棉'],['other','自訂線']],p.thread||'')}${field('色號（線盒繡線才填）','color',p.color)}<label>實物照片（至多兩張）<input type="file" name="photos" accept="image/*" multiple></label>${photos(p.photos)}${p.photos?.length?'<label class="check"><input type="checkbox" name="clearPhotos">移除原有照片（可再選新照片）</label>':''}`,async f=>{
 const name=String(f.get('name')||'').trim(),thread=String(f.get('thread')||''),color=String(f.get('color')||'').trim();if(!name)throw Error('請填品名');
 const canonical=thread==='moul'?DMC.find(x=>x.c.toLowerCase()===color.toLowerCase())?.c:color;if(thread==='moul'&&!canonical)throw Error('找不到這個 DMC 色號');
 if(thread==='other'&&!((App.readThread().custom||[]).some(x=>x.c===color)))throw Error('請先在線盒建立自訂色號');
 let category=String(f.get('newCategory')||'').trim()||String(f.get('category'));if(!db.categories.includes(category))db.categories.push(category);
 let ids=f.get('clearPhotos')?[]:[...(p.photos||[])];ids=await App.saveFiles(form.querySelector('[name=photos]').files,ids);
 Object.assign(p,{id:p.id||id(),name,brand:String(f.get('brand')||''),category,kind:String(f.get('kind')),unit:String(f.get('unit')||'個'),thread,color:canonical,photos:ids,stock:num(p.stock),moves:p.moves||[]});if(!db.products.some(x=>x.id===p.id))db.products.push(p);
 })}
const recentPrice=pid=>{const l=allLines().filter(x=>x.productId===pid).sort((a,b)=>b.date.localeCompare(a.date))[0];return l?.unitPrice||''};
function orderItem(item){const choices=db.products.map(p=>[p.id,[p.name,p.brand,p.color].filter(Boolean).join(' · ')]);return `<div class="itemform"><button type="button" class="remove" data-remove-item>移除</button>${select('商品 *','productId',choices,item?.productId||db.products[0]?.id)}<div class="orderPhoto">${productPhotos(product(item?.productId||db.products[0]?.id))}</div><div class="formgrid">${field('單價 *','unitPrice',item?.unitPrice??recentPrice(item?.productId||db.products[0]?.id),'number','min="0" step="0.01" required')}${field('數量 *','qty',item?.qty||1,'number','min="0.01" step="0.01" required')}</div><label class="check"><input type="checkbox" name="sync" ${item?.sync===false?'':'checked'}>同步入庫（繡線也更新線盒）</label></div>`}
function newOrder(){if(!db.products.length){toast('請先建立常買商品');tab='products';render();return}show(`<h2>登記整筆購買</h2><div class="formgrid">${field('購買日期 *','date',today(),'date','required')}${field('商店','store')}</div>${field('訂單編號','orderNo')}<div class="formgrid">${field('整單運費','shipping',0,'number','min="0" step="0.01"')}${field('整單折扣','discount',0,'number','min="0" step="0.01"')}</div><div id="items">${orderItem()}</div><button type="button" class="smallbtn" id="addItem">＋ 再加一項商品</button>${field('備註','note')}`,async f=>{
 const nodes=[...form.querySelectorAll('.itemform')];if(!nodes.length)throw Error('請至少加一項商品');const lines=nodes.map(n=>{let pid=n.querySelector('[name=productId]').value,p=product(pid),qty=Number(n.querySelector('[name=qty]').value),unitPrice=Number(n.querySelector('[name=unitPrice]').value);if(!p||!Number.isFinite(qty)||qty<=0||!Number.isFinite(unitPrice)||unitPrice<0)throw Error('商品、數量或單價不正確');return {id:id(),productId:pid,qty,unitPrice,sync:n.querySelector('[name=sync]').checked}});
 // 先在記憶體確認所有色號，避免訂單存到一半才發現無法入庫。
 const thread=App.readThread();for(const l of lines){const p=product(l.productId);if(l.sync&&p.thread&&!Number.isInteger(l.qty))throw Error('繡線入庫束數請填整數');if(l.sync&&p.thread==='other'&&!thread.custom?.some(x=>x.c===p.color))throw Error('自訂線色號不存在')}
 db.orders.push({id:id(),date:String(f.get('date')),store:String(f.get('store')||''),orderNo:String(f.get('orderNo')||''),shipping:num(f.get('shipping')),discount:num(f.get('discount')),note:String(f.get('note')||''),lines});for(const l of lines)if(l.sync)syncPurchase(l);
 tab='orders';
 });form.onclick=e=>{if(e.target.id==='addItem'){form.querySelector('#items').insertAdjacentHTML('beforeend',orderItem());paintPhotos()};if(e.target.matches('[data-remove-item]'))e.target.closest('.itemform').remove()};form.onchange=e=>{if(e.target.name==='productId'){const n=e.target.closest('.itemform'),v=recentPrice(e.target.value);n.querySelector('[name=unitPrice]').value=v;n.querySelector('.orderPhoto').innerHTML=productPhotos(product(e.target.value));paintPhotos();}}}
function syncPurchase(l){const p=product(l.productId);if(!p||p.kind==='expense')return;p.stock=num(p.stock)+num(l.qty);p.moves.push({id:id(),date:today(),qty:num(l.qty),note:'購買同步入庫'});if(!p.thread)return;const t=App.readThread();t.stock=t.stock||{};const k=p.thread+':'+p.color;const r=t.stock[k]||{skeins:0,level:'full',wish:false,scrap:false,note:''};r.skeins=num(r.skeins)+num(l.qty);r.wish=false;t.stock[k]=r;p.stock=r.skeins;App.writeThread(t)}
function orderForm(o){show(`<h2>修改訂單資料</h2><div class="formgrid">${field('購買日期','date',o.date,'date','required')}${field('商店','store',o.store)}</div>${field('訂單編號','orderNo',o.orderNo)}<div class="formgrid">${field('整單運費','shipping',o.shipping,'number','min="0" step="0.01"')}${field('整單折扣','discount',o.discount,'number','min="0" step="0.01"')}</div>${field('備註','note',o.note)}`,f=>{Object.assign(o,{date:String(f.get('date')),store:String(f.get('store')),orderNo:String(f.get('orderNo')),shipping:num(f.get('shipping')),discount:num(f.get('discount')),note:String(f.get('note'))})})}
function lineForm(o,l){show(`<h2>修改購買項目</h2><p class="muted">修改商品、數量或單價不會再次入庫；若已同步入庫，請到商品庫存另行調整。</p>${select('商品','productId',db.products.map(p=>[p.id,p.name]),l.productId)}<div class="formgrid">${field('單價','unitPrice',l.unitPrice,'number','min="0" step="0.01" required')}${field('數量','qty',l.qty,'number','min="0.01" step="0.01" required')}</div>`,f=>{l.productId=String(f.get('productId'));l.unitPrice=num(f.get('unitPrice'));l.qty=num(f.get('qty'));if(!l.qty)throw Error('數量需大於 0')})}
function movementForm(p){show(`<h2>${esc(p.name)} · 記使用／庫存</h2><p class="muted">庫存目前 ${stockOf(p)} ${esc(p.unit)}；作品成本與這裡的庫存變動互不影響。</p>${field('日期','date',today(),'date')}${select('動作','action',[['use','用掉／減少'],['add','補入／增加'],['reuse','使用後仍可重複用']],p.kind==='reuse'?'reuse':'use')}${field('數量','qty',1,'number','min="0.01" step="0.01"')}${field('備註／使用於哪件作品','note')}`,f=>{const a=f.get('action'),qty=num(f.get('qty')),delta=a==='reuse'?0:a==='add'?qty:-qty;if(a!=='reuse'&&!qty)throw Error('請填數量');p.stock=Math.max(0,stockOf(p)+delta);p.moves.push({id:id(),date:String(f.get('date')),qty:delta,action:a,note:String(f.get('note')||'')});if(p.thread&&delta){const t=App.readThread();t.stock=t.stock||{};const k=p.thread+':'+p.color,r=t.stock[k]||{skeins:0,level:'full',wish:false,scrap:false,note:''};r.skeins=Math.max(0,num(r.skeins)+delta);t.stock[k]=r;p.stock=r.skeins;App.writeThread(t)}})}
function pieceForm(p){p=p||{};show(`<h2>${p.id?'編輯成本作品':'新增成本作品'}</h2>${field('作品名稱 *','name',p.name,'text','required')}${field('製作日期','madeDate',p.madeDate||today(),'date')}<label>作品照片（至多兩張）<input name="photos" type="file" accept="image/*" multiple></label>${photos(p.photos)}${p.photos?.length?'<label class="check"><input name="clearPhotos" type="checkbox">移除原有照片（可再選新照片）</label>':''}<label>備註<textarea name="note">${esc(p.note||'')}</textarea></label>`,async f=>{const name=String(f.get('name')||'').trim();if(!name)throw Error('請填作品名稱');let pics=f.get('clearPhotos')?[]:[...(p.photos||[])];pics=await App.saveFiles(form.querySelector('[name=photos]').files,pics);Object.assign(p,{id:p.id||id(),name,madeDate:String(f.get('madeDate')||''),photos:pics,note:String(f.get('note')||''),allocations:p.allocations||[],extras:p.extras||[],status:p.status||'待製作'});if(!db.pieces.some(x=>x.id===p.id))db.pieces.push(p);opened=p.id;tab='pieces'})}
function allocationForm(p,a){a=a||{};if(!db.orders.length){toast('請先建立採購紀錄');tab='orders';render();return}
const lines=allLines().sort((x,y)=>y.date.localeCompare(x.date));const pid=a.lineId?line(a.lineId)?.productId:lines[0]?.productId;
const productOptions=[...new Set(lines.map(x=>x.productId))].map(x=>[x,product(x)?.name||'商品']);
const purchaseOptions=pid=>lines.filter(x=>x.productId===pid).map(l=>[l.id,`${l.date} ${l.store||'商店未填'} · ${money(l.unitPrice)}/單位`]);
show(`<h2>${a.id?'修改材料':'加入材料'}</h2>${select('商品','productId',productOptions,pid)}<div id="purchaseSlot">${select('哪一次購買（預設最近一次）','lineId',purchaseOptions(pid),a.lineId||purchaseOptions(pid)[0]?.[0])}</div>${field('單一單位使用比例 %','percent',a.percent??100,'number','min="0.01" step="0.01" required')}<p class="muted">一單位的單價 × 比例。可再次加入同商品，不限制各筆百分比總和。</p>`,f=>{const l=line(String(f.get('lineId'))),percent=Number(f.get('percent'));if(!l||!Number.isFinite(percent)||percent<=0)throw Error('請選購買紀錄並填大於 0 的比例');Object.assign(a,{id:a.id||id(),lineId:l.id,percent});if(!p.allocations.some(x=>x.id===a.id))p.allocations.push(a)});form.querySelector('[name=productId]').onchange=e=>form.querySelector('#purchaseSlot').innerHTML=select('哪一次購買','lineId',purchaseOptions(e.target.value),purchaseOptions(e.target.value)[0]?.[0])}
function extraForm(p,x){x=x||{};show(`<h2>設計／雜項成本</h2>${select('類型','kind',[['設計成本','設計成本'],['雜項成本','雜項成本']],x.kind||'雜項成本')}${field('名稱 *（例：估算人工、客製打版）','name',x.name,'text','required')}${field('估算金額 *','amount',x.amount||0,'number','min="0" step="0.01" required')}`,f=>{const name=String(f.get('name')||'').trim();if(!name)throw Error('請填名稱');Object.assign(x,{id:x.id||id(),kind:String(f.get('kind')),name,amount:num(f.get('amount'))});if(!p.extras.some(z=>z.id===x.id))p.extras.push(x)})}
function statusForm(p){show(`<h2>變更作品進度</h2>${select('訂單狀態','status',['待製作','製作中','待出貨','已寄出','完成','取消'].map(x=>[x,x]),p.status)}`,f=>{p.status=String(f.get('status'))})}
function saleForm(p){const s=p.sale||{};show(`<h2>販售與出貨 · ${esc(p.name)}</h2>${select('訂單狀態','status',['待製作','製作中','待出貨','已寄出','完成','取消'].map(x=>[x,x]),p.status)}<div class="formgrid">${field('販售日期','date',s.date||today(),'date')}${field('販售平台','platform',s.platform)}</div>${field('購買者（自行辨識用，選填）','buyer',s.buyer)}${field('售價','price',s.price||0,'number','min="0" step="0.01"')}${field('買家支付的運費','shippingCharged',s.shippingCharged||0,'number','min="0" step="0.01"')}<div class="formgrid">${field('實際寄件運費','postage',s.postage||0,'number','min="0" step="0.01"')}${field('包材費','packaging',s.packaging||0,'number','min="0" step="0.01"')}</div>${select('平台抽成計算','feeMode',[['fixed','固定金額'],['percent','售價百分比']],s.feeMode||'fixed')}${field('平台抽成金額或百分比','feeValue',s.feeValue||0,'number','min="0" step="0.01"')}${field('寄送方式','shippingMethod',s.shippingMethod)}<div class="formgrid">${field('出貨日期','shipDate',s.shipDate,'date')}${field('訂單編號','orderNo',s.orderNo)}</div><label>備註<textarea name="note">${esc(s.note||'')}</textarea></label>`,f=>{p.status=String(f.get('status'));p.sale={date:String(f.get('date')),platform:String(f.get('platform')||''),buyer:String(f.get('buyer')||''),price:num(f.get('price')),shippingCharged:num(f.get('shippingCharged')),postage:num(f.get('postage')),packaging:num(f.get('packaging')),feeMode:String(f.get('feeMode')),feeValue:num(f.get('feeValue')),shippingMethod:String(f.get('shippingMethod')||''),shipDate:String(f.get('shipDate')||''),orderNo:String(f.get('orderNo')||''),note:String(f.get('note')||'')}})}
root.addEventListener('click',async e=>{const t=e.target.closest('[data-act],[data-tab]');if(!t)return;if(t.dataset.tab){tab=t.dataset.tab;opened=null;search='';render();return}const a=t.dataset.act,k=t.dataset.id,p=piece(k),pr=product(k),ref=t.dataset.ref;
 if(a==='newProduct')return productForm();if(a==='editProduct')return productForm(pr);if(a==='newOrder')return newOrder();if(a==='editOrder')return orderForm(order(k));if(a==='editLine')return lineForm(order(k),order(k).lines.find(x=>x.id===ref));if(a==='movement')return movementForm(pr);
 if(a==='deleteProduct'){if(allLines().some(x=>x.productId===k))return toast('已有購買紀錄的商品不能刪除');if(confirm('刪除這項商品？')){db.products=db.products.filter(x=>x.id!==k);persist()}return}
 if(a==='changeStatus')return statusForm(p);if(a==='newPiece')return pieceForm();if(a==='openPiece'){opened=k;render();return}if(a==='closePiece'){opened=null;render();return}if(a==='editPiece')return pieceForm(p);
 if(a==='duplicatePiece'){const copy={...structuredClone(p),id:id(),name:p.name+'（新的一件）',madeDate:today(),allocations:p.allocations.map(x=>({...x,id:id()})),extras:p.extras.map(x=>({...x,id:id()})),sale:null,status:'待製作'};db.pieces.push(copy);opened=copy.id;persist();toast('已複製，可調整這件的成本');return}
 if(a==='deletePiece'){if(confirm('刪除這件作品及其成本與販售紀錄？')){db.pieces=db.pieces.filter(x=>x.id!==k);opened=null;persist()}return}
 if(a==='addAllocation')return allocationForm(p);if(a==='editAllocation')return allocationForm(p,p.allocations.find(x=>x.id===ref));if(a==='removeAllocation'){p.allocations=p.allocations.filter(x=>x.id!==ref);persist();return}
 if(a==='addExtra')return extraForm(p);if(a==='editExtra')return extraForm(p,p.extras.find(x=>x.id===ref));if(a==='removeExtra'){p.extras=p.extras.filter(x=>x.id!==ref);persist();return}if(a==='saleForm')return saleForm(p);
 if(a==='backup'){try{App.download('線盒完整備份-'+today()+'.json',await App.backup());toast('已下載含照片的備份')}catch(_){toast('備份失敗，請再試一次')}}
});
root.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;const caret=e.target.selectionStart;render();const x=document.getElementById('search');x?.focus();x?.setSelectionRange(caret,caret)}});
root.addEventListener('change',async e=>{if(e.target.id==='restoreFile'){try{const raw=await e.target.files[0].text();if(!confirm('還原會取代目前所有線盒、成本、日曆及照片資料。確定還原？'))return;await App.restore(raw);db=App.readCost();opened=null;render();toast('還原完成')}catch(err){toast('還原失敗，請確認備份檔')}}});
render();
})();
